chore: simplify pipeline commands

diff --git a/.github/workflows/jsr.yml b/.github/workflows/jsr.yml
--- a/.github/workflows/jsr.yml
+++ b/.github/workflows/jsr.yml
@@ -29,11 +29,8 @@ jobs:
             ~/.cache/deno
           key: ${{ runner.os }}-deno-${{ hashFiles('**/pnpm-lock.yaml') }}
       - run: |
-          for pkg in packages/*; do
-            if [ -f "$pkg/jsr.json" ]; then
-              cd $pkg
-              deno publish --dry-run
-              deno publish || echo "Publish failed (possibly already published)"
-              cd -
-            fi
-          done
+          deno lint
+          deno run test
+
+          deno publish --dry-run
+          deno publish || echo "Publish failed (possibly already published)"
